### ISSUE TITLE
Remove deprecated syntax

### ISSUE THREAD

**Issue by nemani** [turnerlabs/terraform-remote-state#8]
Using this module gives 3-4 syntax deprecation warnings which are annoying. 
I have not found any way to quite the warnings. It should be pretty simple to fix and update the code to support TF 0.12+ 
If needed I can send the PR to solve this, otherwise I will go ahead and fork this repo. 

Thanks for the help!

**Comment by jritsema** [comment]
This should have been addressed in the v3 release.  Sorry for not updating this issue sooner.

https://github.com/turnerlabs/terraform-remote-state/releases/tag/v3.0.0
